### ISSUE TITLE
Support .NET 9 / EF Core 9

### ISSUE THREAD

**Issue by Hona** [ClaveConsulting/Expressionify#30]
Looks like some errors in early upgrade tests to .NET 9

![image](https://github.com/user-attachments/assets/31ebc18f-cf90-40f1-bbe6-ad8ab068c9d4)

**Comment by Int32Overflow** [comment]
Same problem here

**Comment by molinch** [comment]
Message:
`Method 'PrecompileQuery' in type 'Clave.Expressionify.ExpressionableQueryCompiler' from assembly 'Clave.Expressionify, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.`

Full stack trace:
```
   at Clave.Expressionify.ExpressionifyDbContextOptionsExtension.ApplyServices(IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ApplyServices(IDbContextOptions options, ServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<GetOrAdd>g__BuildServiceProvider|4_1(IDbContextOptions _, ValueTuple`2 arguments)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c.<GetOrAdd>b__4_0(IDbContextOptions contextOptions, ValueTuple`2 tuples)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at Sofia.Common.PatientModule.Infrastructure.PatientDbContext..ctor(DbContextOptions`1 options, TimeProvider timeProvider) in C:\Users\molinetf\src\sofia\backend\Sofia.Common.PatientModule\Infrastructure\PatientDbContext.cs:line 9
```

**Comment by molinch** [comment]
It's because IQueryCompiler has now:
```
/// <summary>
///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
///     the same compatibility standards as public APIs. It may be changed or removed without notice in
///     any release. You should only use it directly in your code with extreme caution and knowing that
///     doing so can result in application failures when updating to a new Entity Framework Core release.
/// </summary>
[Experimental(EFDiagnostics.PrecompiledQueryExperimental)]
Expression<Func<QueryContext, TResult>> PrecompileQuery<TResult>(Expression query, bool async);
```

And this isn't implemented yet by Clave.Expressionify.ExpressionableQueryCompiler

**Comment by molinch** [comment]
Fix for it in Clave.Expressionify.ExpressionableQueryCompiler:

```csharp
        public Expression<Func<QueryContext, TResult>> PrecompileQuery<TResult>(Expression query, bool async)
        {
#pragma warning disable EF9100 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
            return _decoratedCompiler.PrecompileQuery<TResult>(query, async);
#pragma warning restore EF9100 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
        }
```

But then we should also fix ExpressionifyQueryTranslationPreprocessor as the type ExpressionifyQueryTranslationPreprocessor no longer exist.

**Comment by mariusGundersen** [comment]
Closing at this should be fixed now. Let me know if something isn't working.

**Comment by Hona** [comment]
Awesome work, thanks team!
